// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trhbdcrkolubvgytjkhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyaGJkY3Jrb2x1YnZneXRqa2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDY2MTEsImV4cCI6MjA2ODMyMjYxMX0.WnT3Ni8Nv4_bkgircLfU8hh_mUcV0e1DPMxt2pz-DvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});